# Generated by Django 5.2.4 on 2026-04-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, default='Đang cập nhật', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_instructions',
            field=models.CharField(blank=True, default='Bảo quản nơi khô ráo, thoáng mát', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_volume',
            field=models.CharField(blank=True, default='1 kg', max_length=100, null=True),
        ),
    ]
