# Generated by Django 5.2.4 on 2026-05-25 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_ingredients_product_storage_instructions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mfd',
        ),
    ]
