# Generated by Django 5.2.4 on 2025-11-20 04:51

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_vendor_date_alter_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='cover_image',
            field=models.ImageField(default='vendors.jpg', upload_to=core.models.user_directory_path),
        ),
    ]
