# Generated by Django 5.2.4 on 2026-08-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_cartorder_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Số lượt tối đa. Bỏ trống nghĩa là không giới hạn.', null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='used_count',
            field=models.PositiveIntegerField(default=0, help_text='Số lượt đã dùng. Chỉ tăng khi đơn hàng được xác nhận đã thanh toán.'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(blank=True, help_text='Bỏ trống nghĩa là mã không bao giờ hết hạn.', null=True),
        ),
    ]
