# Generated by Django 5.2.4 on 2026-08-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_coupon_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='vnpay_amount',
            field=models.PositiveBigIntegerField(blank=True, help_text='Số tiền đã gửi sang VNPay (VND × 100). Trống nghĩa là đơn chưa sang cổng.', null=True),
        ),
    ]
