# Generated by Django 5.2.4 on 2026-03-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_cartorder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online'), ('cod', 'Cash on Delivery')], default='online', max_length=20),
        ),
    ]
