"""
Django settings for grocerly project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import urlparse
from django.contrib.messages import constants as messages
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# `DJANGO_SKIP_DOTENV=1` bỏ qua hoàn toàn `.env`.
#
# Hai chỗ cần: môi trường chạy bằng biến môi trường thật (Render, container) không muốn
# một file `.env` sót lại xen vào, và `core/test_settings_security.py` cần nạp lại module
# này với môi trường giả — không có cờ này thì `.env` của máy ghi đè lại ngay, và quy tắc
# suy ra `DEBUG` / `SECRET_KEY` không kiểm chứng được.
_SKIP_DOTENV = os.environ.get('DJANGO_SKIP_DOTENV', '').strip() == '1'

if not _SKIP_DOTENV:
    # Load environment variables from .env file
    load_dotenv(os.path.join(BASE_DIR, '.env'))

    # Manual .env loader (No external library required)
    env_file = BASE_DIR / ".env"
    if env_file.exists():
        with open(env_file) as f:
            for line in f:
                if line.strip() and not line.startswith("#"):
                    try:
                        key, value = line.strip().split("=", 1)
                        os.environ[key] = value
                    except ValueError:
                        continue


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Khóa dự phòng, CHỈ dùng khi DEBUG=True. Không phải khóa cũ: khóa đó đã nằm công khai
# trên GitHub nên không được tiếp tục làm giá trị dự phòng ở bất kỳ môi trường nào.
DEV_SECRET_KEY = 'django-insecure-development-only-do-not-deploy-with-this-key'


def _env_flag(name, default):
    """Đọc một biến môi trường dạng cờ. Chỉ đúng `'1'` mới là bật.

    `.strip()` là bắt buộc, không phải cho đẹp: `.env` được nạp bằng `split('=', 1)`
    thủ công ở đầu file này nên giá trị **giữ nguyên khoảng trắng thừa**, và
    `DJANGO_DEBUG=1 ` với một dấu cách ở cuối từng bị đọc thành tắt.
    """
    return os.environ.get(name, default).strip() == '1'


def _resolve_secret_key(debug):
    """Trả `SECRET_KEY`, hoặc **từ chối khởi động** nếu thiếu ở production — S-05.

    Trước bản vá, thiếu `DJANGO_SECRET_KEY` thì ứng dụng vẫn chạy bình thường bằng một
    khóa mặc định đã công khai trên GitHub. `SECRET_KEY` ký cookie phiên và token đặt lại
    mật khẩu, nên biết khóa là giả mạo được phiên đăng nhập của bất kỳ ai — và không có
    dấu hiệu nào cho thấy điều đó đang xảy ra.

    Sập lúc khởi động ồn ào hơn nhiều so với chạy tiếp bằng khóa ai cũng biết.

    ⚠️ **Trước khi deploy phải xác nhận Render đã đặt `DJANGO_SECRET_KEY`** — xem
    [PLAN.md](../../docs/PLAN.md) bước 1.1. Thiếu nó là site không khởi động được.
    """
    key = os.environ.get('DJANGO_SECRET_KEY', '').strip()
    if key:
        return key
    if not debug:
        raise ImproperlyConfigured(
            "Thiếu biến môi trường DJANGO_SECRET_KEY. Bắt buộc phải đặt khi DEBUG=False: "
            "khóa dự phòng dành cho môi trường dev đã nằm công khai trong repo, dùng nó "
            "ở production nghĩa là bất kỳ ai cũng giả mạo được cookie phiên."
        )
    return DEV_SECRET_KEY


# SECURITY WARNING: don't run with debug turned on in production!
#
# Mặc định là TẮT. Trước đây mặc định là bật, nghĩa là quên đặt biến trên máy chủ thì
# trang lỗi phơi traceback và toàn bộ cấu hình cho bất kỳ ai gõ một URL sai.
DEBUG = _env_flag('DJANGO_DEBUG', '0')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _resolve_secret_key(DEBUG)

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Cookie chỉ được đi qua HTTPS khi không phải môi trường dev — S-11.
#
# Render vốn phục vụ qua HTTPS, nhưng cookie thiếu cờ `Secure` thì trình duyệt vẫn được
# phép gửi nó qua một kết nối HTTP thường nếu có đường nào dẫn tới đó.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    # Third Party
    'cloudinary_storage',
    'cloudinary',
    'taggit',
    'rest_framework',

    # Custom apps
    'core',
    'userauths',
    'useradmin',
    'store_api',
    'django_cleanup.apps.CleanupConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'core.middleware.ForceDefaultLanguageMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'grocerly.middleware.RestrictStaffMiddleware',
]

ROOT_URLCONF = 'grocerly.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'core.context_processors.default',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
                'currency_filters': 'core.templatetags.currency_filters',
            },
        },
    },
]

WSGI_APPLICATION = 'grocerly.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Prioritize PostgreSQL if POSTGRES_DB is set, otherwise use DATABASE_URL, else fallback to SQLite.

_db_name = os.environ.get('POSTGRES_DB')
_database_url = os.environ.get('DATABASE_URL')

if _db_name:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _db_name,
            'USER': os.environ.get('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
            'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }
    }
elif _database_url:
    _parsed = urlparse(_database_url)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _parsed.path.lstrip('/'),
            'USER': _parsed.username or '',
            'PASSWORD': _parsed.password or '',
            'HOST': _parsed.hostname or 'localhost',
            'PORT': str(_parsed.port or 5432),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGES = [
    ('vi', _('Vietnamese')),
    ('en', _('English')),
]

LANGUAGE_CODE = 'vi'

# Set the timezone to Asia/Ho_Chi_Minh
TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

USE_CLOUDINARY = os.environ.get('USE_CLOUDINARY', 'False').lower() == 'true'

if USE_CLOUDINARY:
    import cloudinary
    import cloudinary.uploader
    import cloudinary.api
    
    STORAGES = {
        "default": {"BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage"},
        "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
    }
else:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
    }

WHITENOISE_MANIFEST_STRICT = False


# Django REST Framework — xem store_api/throttling.py và SECURITY.md S-03.
#
# Hạn mức chọn rộng tay có chủ ý: lúc bảo vệ, nhiều người xem cùng ngồi sau một địa chỉ
# IP (NAT), đặt quá chặt là tự khóa buổi demo. Mục tiêu ở đây là chặn script quét hàng
# nghìn lượt, không phải bóp người dùng thật.
REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'store_api.throttling.chat_exception_handler',
    'DEFAULT_THROTTLE_RATES': {
        'ai_chat_anon': '60/hour',
        'ai_chat_user': '120/hour',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Jazzmin settings
JAZZMIN_SETTINGS = {
    "site_title": "Quản trị Grocerly",
    "site_header": "Hệ thống Quản trị Grocerly",
    "site_brand": "Quản trị Grocerly",
    # "site_logo": "",
    "copyright": "Grocerly",
    "welcome_sign": "Chào mừng đến với Hệ thống Quản trị Grocerly",
    "topmenu_links": [
        {"name": "Trang chủ",  "url": "admin:index", "permissions": ["auth.view_user"]},
    ],
    "usermenu_links": [
        {"name": "Về trang UserAdmin", "url": "/useradmin/", "icon": "fas fa-tachometer-alt", "new_window": False},
    ],
    "custom_js": "assets2/js/admin_custom.js",
}


AUTH_USER_MODEL = 'userauths.User'


# VNPay settings
VNPAY_TMN_CODE = os.environ.get('VNPAY_TMN_CODE', '')
VNPAY_HASH_SECRET = os.environ.get('VNPAY_HASH_SECRET', '')
VNPAY_PAYMENT_URL = os.environ.get('VNPAY_PAYMENT_URL', '')
# We will construct VNPAY_RETURN_URL dynamically in views.py using request.build_absolute_uri
VNPAY_API_URL = os.environ.get('VNPAY_API_URL', '')


# Authentication URLs
LOGIN_URL = 'userauths:sign-in'
LOGIN_REDIRECT_URL = 'core:index'
LOGOUT_REDIRECT_URL = 'userauths:sign-in'


# Map Django message levels to Bootstrap CSS classes
MESSAGE_TAGS = {
    messages.ERROR: 'danger',
}

# EMAIL SETTINGS
# For development/testing: Print emails to the console instead of sending real ones
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# For Production (Uncomment and configure .env variables to use Gmail SMTP)
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER') # Your Gmail address
# EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD') # App Password